#pragma once
#ifndef WINDOWCONTEINERENUM_H
#define WINDOWCONTEINERENUM_H

enum WINDOWS_DESCRIPTIONS
{
    NONE = -1,
    MAIN_WINDOW = 0,
    WINDOW_ONE,
    WINDOW_TWO,
    WINDOW_THREE,
    WINDOW_FOUR
};  

#endif